// =============================================================================
// Host Application: Conv2D via pre-built single-op model (OpsBuilder / atc)
// =============================================================================
//
// Execution flow:
//   1. Initialize ACL runtime and select device
//   2. Create context + stream, set model directory
//   3. Load the pre-built Conv2D .om model generated by atc
//   4. Prepare input (NCHW: 1x1x8x8), weight (1x1x3x3), and bias (1) tensors
//   5. Build input/output Datasets and execute model
//   6. Copy output (1x1x6x6) to host and verify against CPU reference

use anyhow::{Context, Result};
use ascend_rs::prelude::*;
use log::info;
use simple_logger::SimpleLogger;
use std::ffi::c_void;

/// CPU reference: 2D convolution (single batch, single channel, no padding, stride=1).
fn cpu_conv2d(
    input: &[f32],
    weight: &[f32],
    bias: f32,
    in_h: usize,
    in_w: usize,
    kh: usize,
    kw: usize,
) -> Vec<f32> {
    let out_h = in_h - kh + 1;
    let out_w = in_w - kw + 1;
    let mut output = vec![0.0f32; out_h * out_w];
    for oh in 0..out_h {
        for ow in 0..out_w {
            let mut sum = bias;
            for r in 0..kh {
                for c in 0..kw {
                    sum += input[(oh + r) * in_w + (ow + c)] * weight[r * kw + c];
                }
            }
            output[oh * out_w + ow] = sum;
        }
    }
    output
}

fn main() -> Result<()> {
    SimpleLogger::new()
        .init()
        .context("Failed to initialize logger")?;

    // -- Step 1: Initialize ACL and select device ----------------------------
    info!("Initializing ACL...");
    let mut acl = Acl::new()?;
    let device = Device::new(&acl)?;
    info!("Device initialized: {}", device.id());

    // -- Step 2: Create context and stream -----------------------------------
    let context = AclContext::new(&device)?;
    let stream = AclStream::new(&context)?;

    acl.set_model_dir("test_data/op_models")
        .context("Failed to set model directory")?;
    info!("Model directory set to 'test_data/op_models'");

    // -- Step 3: Prepare input data ------------------------------------------
    let in_h = 8usize;
    let in_w = 8usize;
    let kh = 3usize;
    let kw = 3usize;
    let out_h = in_h - kh + 1; // 6
    let out_w = in_w - kw + 1; // 6

    let input_f32: Vec<f32> = (0..in_h * in_w).map(|i| (i as f32) * 0.1).collect();
    let weight_f32: Vec<f32> = vec![1.0, 0.0, -1.0, 2.0, 0.0, -2.0, 1.0, 0.0, -1.0];
    let bias_f32: f32 = 0.5;

    // Convert to f16 for device
    let input_f16: Vec<AclFloat16> = input_f32.iter().map(|&v| AclFloat16::from(v)).collect();
    let weight_f16: Vec<AclFloat16> = weight_f32.iter().map(|&v| AclFloat16::from(v)).collect();
    let bias_f16: Vec<AclFloat16> = vec![AclFloat16::from(bias_f32)];

    // CPU reference (computed in f32)
    let expected = cpu_conv2d(&input_f32, &weight_f32, bias_f32, in_h, in_w, kh, kw);

    // -- Step 4: Allocate device memory and copy data ------------------------
    let d_input = DeviceBuffer::from_slice(&input_f16)?;
    let d_weight = DeviceBuffer::from_slice(&weight_f16)?;
    let d_bias = DeviceBuffer::from_slice(&bias_f16)?;
    let mut d_output = unsafe { DeviceBuffer::<AclFloat16>::uninitialized(out_h * out_w)? };

    // -- Step 5: Load model and build datasets -------------------------------
    // atc generates the .om file name based on the op type
    let model = Model::from_file("test_data/op_models/0_Conv2D_0_0_0_0_0_0_0.om")?;
    let desc = model.description()?;
    info!(
        "Model loaded: {} inputs, {} outputs",
        desc.num_inputs(),
        desc.num_outputs()
    );

    // Build input dataset
    let input_buf = unsafe {
        DataBuffer::new(
            d_input.as_ptr() as *mut c_void,
            d_input.len() * std::mem::size_of::<AclFloat16>(),
        )?
    };
    let weight_buf = unsafe {
        DataBuffer::new(
            d_weight.as_ptr() as *mut c_void,
            d_weight.len() * std::mem::size_of::<AclFloat16>(),
        )?
    };
    let bias_buf = unsafe {
        DataBuffer::new(
            d_bias.as_ptr() as *mut c_void,
            d_bias.len() * std::mem::size_of::<AclFloat16>(),
        )?
    };

    let mut input_dataset = Dataset::new()?;
    input_dataset.add_buffer(&input_buf)?;
    input_dataset.add_buffer(&weight_buf)?;
    input_dataset.add_buffer(&bias_buf)?;

    // Build output dataset
    let output_buf = unsafe {
        DataBuffer::new(
            d_output.as_mut_ptr() as *mut c_void,
            d_output.len() * std::mem::size_of::<AclFloat16>(),
        )?
    };
    let mut output_dataset = Dataset::new()?;
    output_dataset.add_buffer(&output_buf)?;

    // -- Step 6: Execute model -----------------------------------------------
    info!("Executing Conv2D...");
    model.execute(&input_dataset, &mut output_dataset)?;

    // -- Step 7: Copy results to host and verify -----------------------------
    let result_f16 = d_output.to_host()?;
    let result_f32: Vec<f32> = result_f16.iter().map(|v| f32::from(*v)).collect();

    info!("Output ({}x{}):", out_h, out_w);
    for oh in 0..out_h {
        let row: Vec<String> = (0..out_w)
            .map(|ow| format!("{:>8.3}", result_f32[oh * out_w + ow]))
            .collect();
        info!("  {}", row.join(" "));
    }

    info!(
        "Verifying {} results against CPU reference...",
        expected.len()
    );
    for (idx, (got, exp)) in result_f32.iter().zip(expected.iter()).enumerate() {
        let diff = (got - exp).abs();
        assert!(
            diff < 0.5, // f16 has limited precision
            "mismatch at index {}: got {}, expected {}, diff {}",
            idx,
            got,
            exp,
            diff
        );
    }
    info!("All results correct!");

    Ok(())
}
