// Generated by tile-rs mlir_to_msl — inference helper kernels
// Additional kernels needed for LLM inference pipeline
#include <metal_stdlib>
using namespace metal;

// ── bf16 → f32 conversion ───────────────────────────────────────────────────
// bfloat16 is stored as uint16_t, convert by shifting left 16 bits
kernel void bf16_to_f32(
    device const ushort* src [[ buffer(0) ]],
    device float*        dst [[ buffer(1) ]],
    constant uint&       N   [[ buffer(2) ]],
    uint gid [[ thread_position_in_grid ]]
)
{
    if (gid >= N) return;
    uint bits = uint(src[gid]) << 16;
    dst[gid] = as_type<float>(bits);
}

// ── Embedding lookup ────────────────────────────────────────────────────────
// out[i, :] = table[tokens[i], :]
kernel void embedding(
    device const float*  table  [[ buffer(0) ]],   // (vocab, dim)
    device const uint*   tokens [[ buffer(1) ]],   // (seq_len,)
    device float*        out    [[ buffer(2) ]],   // (seq_len, dim)
    constant uint&       dim    [[ buffer(3) ]],
    uint gid [[ thread_position_in_grid ]]
)
{
    uint seq_idx = gid / dim;
    uint d       = gid % dim;
    uint token   = tokens[seq_idx];
    out[gid] = table[token * dim + d];
}

// ── Element-wise multiply (for gated MLP) ───────────────────────────────────
// out[i] = a[i] * b[i]
kernel void elementwise_mul(
    device const float* a   [[ buffer(0) ]],
    device const float* b   [[ buffer(1) ]],
    device float*       out [[ buffer(2) ]],
    constant uint&      N   [[ buffer(3) ]],
    uint gid [[ thread_position_in_grid ]]
)
{
    if (gid >= N) return;
    out[gid] = a[gid] * b[gid];
}

// ── Element-wise add (residual connection) ──────────────────────────────────
kernel void elementwise_add(
    device const float* a   [[ buffer(0) ]],
    device const float* b   [[ buffer(1) ]],
    device float*       out [[ buffer(2) ]],
    constant uint&      N   [[ buffer(3) ]],
    uint gid [[ thread_position_in_grid ]]
)
{
    if (gid >= N) return;
    out[gid] = a[gid] + b[gid];
}

// ── Matmul with bias (for QKV projections) ──────────────────────────────────
// C[i,j] = sum_k A[i,k] * B[k,j] + bias[j]
kernel void matmul_bias(
    device const float* A    [[ buffer(0) ]],   // (M, K)
    device const float* B    [[ buffer(1) ]],   // (K, N)
    device float*       C    [[ buffer(2) ]],   // (M, N)
    device const float* bias [[ buffer(3) ]],   // (N,)
    constant uint&      M    [[ buffer(4) ]],
    constant uint&      K    [[ buffer(5) ]],
    constant uint&      N    [[ buffer(6) ]],
    uint gid [[ thread_position_in_grid ]]
)
{
    if (gid >= M * N) return;
    uint row = gid / N;
    uint col = gid % N;
    float sum = bias[col];
    for (uint k = 0; k < K; k++) {
        sum += A[row * K + k] * B[k * N + col];
    }
    C[row * N + col] = sum;
}

// ── GQA attention (grouped query attention) ─────────────────────────────────
// Q: (num_heads, S, head_dim), K/V: (num_kv_heads, S, head_dim)
// Each Q head group shares the same KV head
kernel void attention_gqa(
    device const float* Q   [[ buffer(0) ]],
    device const float* K   [[ buffer(1) ]],
    device const float* V   [[ buffer(2) ]],
    device float*       out [[ buffer(3) ]],
    constant uint&      seq_len   [[ buffer(4) ]],
    constant uint&      head_dim  [[ buffer(5) ]],
    constant uint&      num_heads [[ buffer(6) ]],
    constant uint&      num_kv_heads [[ buffer(7) ]],
    constant uint&      causal    [[ buffer(8) ]],
    uint tid    [[ thread_position_in_threadgroup ]],
    uint head   [[ threadgroup_position_in_grid ]],
    uint tcount [[ threads_per_threadgroup ]]
)
{
    float scale = rsqrt(float(head_dim));
    uint group_size = num_heads / num_kv_heads;
    uint kv_head = head / group_size;

    uint q_off  = head    * seq_len * head_dim;
    uint kv_off = kv_head * seq_len * head_dim;

    for (uint q_row = tid; q_row < seq_len; q_row += tcount) {
        float scores[256];
        float max_score = -MAXFLOAT;
        uint effective_len = min(seq_len, 256u);

        for (uint k_col = 0; k_col < effective_len; k_col++) {
            float dot = 0.0;
            for (uint d = 0; d < head_dim; d++) {
                dot += Q[q_off + q_row * head_dim + d] *
                       K[kv_off + k_col * head_dim + d];
            }
            dot *= scale;
            if (causal && k_col > q_row) dot = -MAXFLOAT;
            scores[k_col] = dot;
            max_score = max(max_score, dot);
        }

        float sum_exp = 0.0;
        for (uint k = 0; k < effective_len; k++) {
            scores[k] = exp(scores[k] - max_score);
            sum_exp += scores[k];
        }
        for (uint k = 0; k < effective_len; k++) {
            scores[k] /= sum_exp;
        }

        for (uint d = 0; d < head_dim; d++) {
            float val = 0.0;
            for (uint k = 0; k < effective_len; k++) {
                val += scores[k] * V[kv_off + k * head_dim + d];
            }
            out[q_off + q_row * head_dim + d] = val;
        }
    }
}

// ── Argmax (greedy token selection) ─────────────────────────────────────────
// Finds argmax over the last row's logits
kernel void argmax_last(
    device const float* logits [[ buffer(0) ]],   // (seq_len, vocab)
    device uint*        result [[ buffer(1) ]],   // (1,)
    constant uint&      seq_len [[ buffer(2) ]],
    constant uint&      vocab   [[ buffer(3) ]],
    uint tid    [[ thread_position_in_threadgroup ]],
    uint tcount [[ threads_per_threadgroup ]]
)
{
    // Only process last row
    uint base = (seq_len - 1) * vocab;

    threadgroup float smax[256];
    threadgroup uint  sidx[256];

    float local_max = -MAXFLOAT;
    uint  local_idx = 0;
    for (uint i = tid; i < vocab; i += tcount) {
        float v = logits[base + i];
        if (v > local_max) {
            local_max = v;
            local_idx = i;
        }
    }
    smax[tid] = local_max;
    sidx[tid] = local_idx;
    threadgroup_barrier(mem_flags::mem_threadgroup);

    for (uint s = tcount/2; s > 0; s >>= 1) {
        if (tid < s) {
            if (smax[tid + s] > smax[tid]) {
                smax[tid] = smax[tid + s];
                sidx[tid] = sidx[tid + s];
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    if (tid == 0) result[0] = sidx[0];
}

// ── Copy single row (for KV cache append) ───────────────────────────────────
kernel void copy_row(
    device const float* src [[ buffer(0) ]],
    device float*       dst [[ buffer(1) ]],
    constant uint&      src_row [[ buffer(2) ]],
    constant uint&      dst_row [[ buffer(3) ]],
    constant uint&      cols    [[ buffer(4) ]],
    uint gid [[ thread_position_in_grid ]]
)
{
    if (gid >= cols) return;
    dst[dst_row * cols + gid] = src[src_row * cols + gid];
}

// ── RoPE with variable position (for decode step) ───────────────────────────
// Applies RoPE to a single row at a given position
kernel void rope_single(
    device float*       x    [[ buffer(0) ]],   // (head_dim,) — in-place
    constant uint&      dim  [[ buffer(1) ]],
    constant uint&      pos  [[ buffer(2) ]],
    constant float&     theta [[ buffer(3) ]],
    uint gid [[ thread_position_in_grid ]]
)
{
    uint half_dim = dim / 2;
    if (gid >= half_dim) return;
    float freq = 1.0 / pow(theta, 2.0 * float(gid) / float(dim));
    float angle = float(pos) * freq;
    float cos_a = cos(angle);
    float sin_a = sin(angle);
    float x0 = x[2*gid];
    float x1 = x[2*gid + 1];
    x[2*gid]     = x0 * cos_a - x1 * sin_a;
    x[2*gid + 1] = x0 * sin_a + x1 * cos_a;
}
