// Generated by tile-rs mlir_to_msl — matmul_transposed
// C[i,j] = sum_k A[i,k] * B[j,k]   (B is transposed: stored as (N, K))
// Used for LLM inference where HF weights are (out_features, in_features)
// Tiled with threadgroup shared memory for M4 GPU efficiency
//
// Dispatch: (ceil(M*N/256), 1, 1)   — simple version
// Dispatch: (ceil(N/TILE_N) * ceil(M/TILE_M), 1, 1) — tiled version
#include <metal_stdlib>
using namespace metal;

// ── Simple element-per-thread (fallback for small matrices) ─────────────────

kernel void matmul_transposed(
    device const float* A   [[ buffer(0) ]],   // (M, K)
    device const float* B   [[ buffer(1) ]],   // (N, K) — transposed
    device float*       C   [[ buffer(2) ]],   // (M, N)
    constant uint&      M   [[ buffer(3) ]],
    constant uint&      K   [[ buffer(4) ]],
    constant uint&      N   [[ buffer(5) ]],
    uint gid [[ thread_position_in_grid ]]
)
{
    if (gid >= M * N) return;
    uint row = gid / N;
    uint col = gid % N;

    float sum = 0.0;
    // Unroll by 4 for better pipelining
    uint k = 0;
    for (; k + 3 < K; k += 4) {
        sum += A[row * K + k]     * B[col * K + k];
        sum += A[row * K + k + 1] * B[col * K + k + 1];
        sum += A[row * K + k + 2] * B[col * K + k + 2];
        sum += A[row * K + k + 3] * B[col * K + k + 3];
    }
    for (; k < K; k++) {
        sum += A[row * K + k] * B[col * K + k];
    }
    C[row * N + col] = sum;
}

// ── With bias: C[i,j] = sum_k A[i,k] * B[j,k] + bias[j] ──────────────────

kernel void matmul_transposed_bias(
    device const float* A    [[ buffer(0) ]],   // (M, K)
    device const float* B    [[ buffer(1) ]],   // (N, K) — transposed
    device float*       C    [[ buffer(2) ]],   // (M, N)
    device const float* bias [[ buffer(3) ]],   // (N,)
    constant uint&      M    [[ buffer(4) ]],
    constant uint&      K    [[ buffer(5) ]],
    constant uint&      N    [[ buffer(6) ]],
    uint gid [[ thread_position_in_grid ]]
)
{
    if (gid >= M * N) return;
    uint row = gid / N;
    uint col = gid % N;

    float sum = bias[col];
    uint k = 0;
    for (; k + 3 < K; k += 4) {
        sum += A[row * K + k]     * B[col * K + k];
        sum += A[row * K + k + 1] * B[col * K + k + 1];
        sum += A[row * K + k + 2] * B[col * K + k + 2];
        sum += A[row * K + k + 3] * B[col * K + k + 3];
    }
    for (; k < K; k++) {
        sum += A[row * K + k] * B[col * K + k];
    }
    C[row * N + col] = sum;
}

// ── Tiled matmul_transposed with shared memory ─────────────────────────────
// Uses TILE_M x TILE_N threadgroup tiles, each thread computes one element.
// Loads K-dim in TILE_K chunks into threadgroup memory for reuse.
//
// Dispatch: (ceil(N/TILE_N), ceil(M/TILE_M), 1) — 2D grid

constant constexpr uint TILE_M = 8;
constant constexpr uint TILE_N = 32;
constant constexpr uint TILE_K = 32;

kernel void matmul_transposed_tiled(
    device const float* A   [[ buffer(0) ]],   // (M, K)
    device const float* B   [[ buffer(1) ]],   // (N, K) — transposed
    device float*       C   [[ buffer(2) ]],   // (M, N)
    constant uint&      M   [[ buffer(3) ]],
    constant uint&      K   [[ buffer(4) ]],
    constant uint&      N   [[ buffer(5) ]],
    uint2 group_id  [[ threadgroup_position_in_grid ]],
    uint2 local_id  [[ thread_position_in_threadgroup ]],
    uint2 tg_size   [[ threads_per_threadgroup ]]
)
{
    // Each threadgroup computes a TILE_M x TILE_N block of C
    uint row_start = group_id.y * TILE_M;
    uint col_start = group_id.x * TILE_N;

    uint local_row = local_id.y;  // 0..TILE_M-1
    uint local_col = local_id.x;  // 0..TILE_N-1

    uint global_row = row_start + local_row;
    uint global_col = col_start + local_col;

    if (global_row >= M || global_col >= N) return;

    // Shared memory tiles
    threadgroup float tileA[TILE_M][TILE_K];
    threadgroup float tileB[TILE_N][TILE_K];

    float sum = 0.0;

    for (uint k_base = 0; k_base < K; k_base += TILE_K) {
        // Load A tile: each thread loads elements for its row
        for (uint kk = local_col; kk < TILE_K && (k_base + kk) < K; kk += TILE_N) {
            if (global_row < M)
                tileA[local_row][kk] = A[global_row * K + k_base + kk];
            else
                tileA[local_row][kk] = 0.0;
        }

        // Load B tile: B is (N, K), so B[col, k]
        for (uint kk = local_row; kk < TILE_K && (k_base + kk) < K; kk += TILE_M) {
            if (global_col < N)
                tileB[local_col][kk] = B[global_col * K + k_base + kk];
            else
                tileB[local_col][kk] = 0.0;
        }

        threadgroup_barrier(mem_flags::mem_threadgroup);

        // Compute partial dot product
        uint k_end = min(TILE_K, K - k_base);
        for (uint kk = 0; kk < k_end; kk++) {
            sum += tileA[local_row][kk] * tileB[local_col][kk];
        }

        threadgroup_barrier(mem_flags::mem_threadgroup);
    }

    C[global_row * N + global_col] = sum;
}
