[package]
name = "tile_matmul"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
libloading = "0.8"
log = "0.4.26"
simple_logger = "5.0.0"
ascend_rs = { path = "../../crates/ascend_rs", default-features = false }

[build-dependencies]
tile_kernel_builder = { path = "../../crates/tile_kernel_builder" }
